// <auto-generated />
using EDAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EDAPI.Migrations
{
    [DbContext(typeof(DeviceContext))]
    [Migration("20200707152457_Added-More-Seed-Data")]
    partial class AddedMoreSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EDAPI.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            DeviceName = "IPhone_4",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 5,
                            DeviceName = "Apple Watch_5",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 6,
                            DeviceName = "Macbook_6",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 7,
                            DeviceName = "IPhone_7",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 8,
                            DeviceName = "Apple Watch_8",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 9,
                            DeviceName = "Macbook_9",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 10,
                            DeviceName = "IPhone_10",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 11,
                            DeviceName = "Apple Watch_11",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 12,
                            DeviceName = "Macbook_12",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 13,
                            DeviceName = "IPhone_13",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 14,
                            DeviceName = "Apple Watch_14",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 15,
                            DeviceName = "Macbook_15",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 16,
                            DeviceName = "IPhone_16",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 17,
                            DeviceName = "Apple Watch_17",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 18,
                            DeviceName = "Macbook_18",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 19,
                            DeviceName = "IPhone_19",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 20,
                            DeviceName = "Apple Watch_20",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 21,
                            DeviceName = "Macbook_21",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 22,
                            DeviceName = "IPhone_22",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 23,
                            DeviceName = "Apple Watch_23",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 24,
                            DeviceName = "Macbook_24",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 25,
                            DeviceName = "IPhone_25",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 26,
                            DeviceName = "Apple Watch_26",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 27,
                            DeviceName = "Macbook_27",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 28,
                            DeviceName = "IPhone_28",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 29,
                            DeviceName = "Apple Watch_29",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 30,
                            DeviceName = "Macbook_30",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 31,
                            DeviceName = "IPhone_31",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 32,
                            DeviceName = "Apple Watch_32",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 33,
                            DeviceName = "Macbook_33",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 34,
                            DeviceName = "IPhone_34",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 35,
                            DeviceName = "Apple Watch_35",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 36,
                            DeviceName = "Macbook_36",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 37,
                            DeviceName = "IPhone_37",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 38,
                            DeviceName = "Apple Watch_38",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 39,
                            DeviceName = "Macbook_39",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 40,
                            DeviceName = "IPhone_40",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 41,
                            DeviceName = "Apple Watch_41",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 42,
                            DeviceName = "Macbook_42",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 43,
                            DeviceName = "IPhone_43",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 44,
                            DeviceName = "Apple Watch_44",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 45,
                            DeviceName = "Macbook_45",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 46,
                            DeviceName = "IPhone_46",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 47,
                            DeviceName = "Apple Watch_47",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 48,
                            DeviceName = "Macbook_48",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 49,
                            DeviceName = "IPhone_49",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 50,
                            DeviceName = "Apple Watch_50",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 51,
                            DeviceName = "Macbook_51",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 52,
                            DeviceName = "IPhone_52",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 53,
                            DeviceName = "Apple Watch_53",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 54,
                            DeviceName = "Macbook_54",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 55,
                            DeviceName = "IPhone_55",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 56,
                            DeviceName = "Apple Watch_56",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 57,
                            DeviceName = "Macbook_57",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 58,
                            DeviceName = "IPhone_58",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 59,
                            DeviceName = "Apple Watch_59",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 60,
                            DeviceName = "Macbook_60",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 61,
                            DeviceName = "IPhone_61",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 62,
                            DeviceName = "Apple Watch_62",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 63,
                            DeviceName = "Macbook_63",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 64,
                            DeviceName = "IPhone_64",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 65,
                            DeviceName = "Apple Watch_65",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 66,
                            DeviceName = "Macbook_66",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 67,
                            DeviceName = "IPhone_67",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 68,
                            DeviceName = "Apple Watch_68",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 69,
                            DeviceName = "Macbook_69",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 70,
                            DeviceName = "IPhone_70",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 71,
                            DeviceName = "Apple Watch_71",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 72,
                            DeviceName = "Macbook_72",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 73,
                            DeviceName = "IPhone_73",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 74,
                            DeviceName = "Apple Watch_74",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 75,
                            DeviceName = "Macbook_75",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 76,
                            DeviceName = "IPhone_76",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 77,
                            DeviceName = "Apple Watch_77",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 78,
                            DeviceName = "Macbook_78",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 79,
                            DeviceName = "IPhone_79",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 80,
                            DeviceName = "Apple Watch_80",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 81,
                            DeviceName = "Macbook_81",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 82,
                            DeviceName = "IPhone_82",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 83,
                            DeviceName = "Apple Watch_83",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 84,
                            DeviceName = "Macbook_84",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 85,
                            DeviceName = "IPhone_85",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 86,
                            DeviceName = "Apple Watch_86",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 87,
                            DeviceName = "Macbook_87",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 88,
                            DeviceName = "IPhone_88",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 89,
                            DeviceName = "Apple Watch_89",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 90,
                            DeviceName = "Macbook_90",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 91,
                            DeviceName = "IPhone_91",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 92,
                            DeviceName = "Apple Watch_92",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 93,
                            DeviceName = "Macbook_93",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 94,
                            DeviceName = "IPhone_94",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 95,
                            DeviceName = "Apple Watch_95",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 96,
                            DeviceName = "Macbook_96",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 97,
                            DeviceName = "IPhone_97",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 98,
                            DeviceName = "Apple Watch_98",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 99,
                            DeviceName = "Macbook_99",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 100,
                            DeviceName = "IPhone_100",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 101,
                            DeviceName = "Apple Watch_101",
                            Make = "Apple"
                        },
                        new
                        {
                            Id = 102,
                            DeviceName = "Macbook_102",
                            Make = "Apple"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
